### ISSUE TITLE
"Analysis" isn't changed to "Analysus"

### ISSUE THREAD

**Issue by SpinahVieh** [Ashvin-Ranjan/Amoguschess#1]
Literally unplayable.

**Comment by keffkeff** [comment]
This issue is resolved in PR #2.

**Comment by Ashvin-Ranjan** [comment]
Will close when I finally get the motivation to publish changes to google extensions

**Comment by Ashvin-Ranjan** [comment]
Its going through review now as `1.0.2` (Don't question why its not a new major version, I just forgot that's how it works). It will probably take 3-5 days to get through.
